version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongo

  app:
    build: ./app
    container_name: react_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  # mongo-import: 
  #   image: mongo:latest
  #   volumes: 
  #     - ./pastries.json:/tmp/pastries.json
  #   depends_on:
  #     - mongo
  #   command: >
  #     sh -c '
  #       mongoimport --host mongo:27017 --db yams_db --collection pastries --jsonArray --type json --file /tmp/pastries.json &&
  #       mongo --host mongo:27017 <<EOF
  #       use yams_db
  #       db.createCollection("users")
  #       db.createCollection("winners")
  #       EOF
  #     '